name: Deploy container

on:
  push:
    branches: [ main ]
    
# The build jobs that run sequentially
jobs:
  build:
    # The Docker build will run on
    runs-on: ubuntu-latest

    # Tasks that will be executed as part of the job
    steps:
      
      # Install the Heroku CLI
      - name: Deploy container to Heroku
      - uses: actions/checkout@v2
      - uses: joverton/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "SJCT" #Must be unique in Heroku
          heroku_email: "joverton@dxc.com"
          usedocker: true
          
            
