# This is a basic workflow to help you get started with Actions

name: Structured Journalism Content Templates Build

# Initiate a Docker build any time there is a new push to the main branch
on:
  push:
    branches: [ main ]

# The build jobs that run sequentially
jobs:
  build:
    # The Docker build will run on
    runs-on: ubuntu-latest

    # Tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Define the DockerHub credentials and log in
      - name: docker login
        env:
          DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}  
          DOCKER_HUB_PWD: ${{secrets.DOCKER_HUB_PWD}}
        run: |
          docker login docker.io -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
          

      # Runs the Docker build as a series of commands using the runners shell
      - name: docker build
        run: |
          docker build ./Code/MiniSite -t jerryaoverton/structured-journalism-content-template:latest
          
      # Push the new image to DockerHub
      - name: docker hub push
        run: |
          docker push jerryaoverton/structured-journalism-content-template:latest
