# This is a basic workflow to help you get started with Actions

name: Structured Journalism Content Templates Build

# Initiate a Docker build any time there is a new push to the main branch
on:
  push:
    branches: [ main ]

# The build jobs that run sequentially
jobs:
  build:
    # The Docker build will run on
    runs-on: ubuntu-latest

    # Tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs the Docker build as a series of commands using the runners shell
      - name: docker build
        run: |
          docker build ./Code/MiniSite -t latest
