# This is a basic workflow to help you get started with Actions

name: Build the container and deploy to Heroku

# Initiate a Docker build any time there is a new push to the main branch
on:
  push:
    branches: [ main ]

# The build jobs that run sequentially
jobs:
  build:
    # The Docker build will run on
    runs-on: ubuntu-latest

    # Tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Define the DockerHub credentials and log in
      - name: docker login
        env:
          DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}  
          DOCKER_HUB_PWD: ${{secrets.DOCKER_HUB_PWD}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
        run: |
          docker login docker.io -u $HEROKU_EMAIL -p $HEROKU_API_KEY registry.heroku.com
          
      # Runs the Docker build as a series of commands using the runners shell
      - name: docker build
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: |
          docker build ./Code/MiniSite -t registry.heroku.com/$HEROKU_APP_NAME/web
          
      # Push the new image to Heroku
      - name: docker hub push
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: |
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
